### ISSUE TITLE
Выровнять заголовок

### ISSUE THREAD

**Issue by Neon4ik35** [ecvanya/hairsalon#3]
Необходимо выровнять заголовок "**Клиенты всегда в приоритете**" относительно текста под ним.

**Comment by Fro1yao** [comment]
Давай реще!

**Comment by Fro1yao** [comment]
ОЧЕНЬ ДОЛГО!!!! ОтВрАтИтЕлЬнО ДОЛГОООО!!!!!! Не приятно на самом деле вообще!

**Comment by Soulbrain24** [comment]
САША И ВАНЯ САСАТЬ

**Comment by Soulbrain24** [comment]
Исправлено, принимайте исправления

**Comment by Fro1yao** [comment]
Ну наконец-то

**Comment by Neon4ik35** [comment]
Yra, molodec harosh megaharosh top molodets emae gotovo
