### ISSUE TITLE
Оптимизация index.html 

### ISSUE THREAD

**Issue by Fro1yao** [ecvanya/hairsalon#4]
Нужно кароче весь код кароче красивым сделать и все и Антон это сделает

**Comment by TonyKurts** [comment]
ладна...

**Comment by Neon4ik35** [comment]
pfxtv gbcfnm nfrjt eckjdbt, tckb 'nj dsgjkyztn jghtltktyysq xtkjdtr f,j,f [f[f[f[f[f[[

**Comment by TonyKurts** [comment]
бимбамбомпиммампапдядьтеть
