### ISSUE TITLE
Сноски на кнопках

### ISSUE THREAD

**Issue by Soulbrain24** [ecvanya/hairsalon#5]
![image](https://user-images.githubusercontent.com/90244865/162686051-b69df939-84e9-4901-8383-7fd8d7ce27d5.png)
Сделать сноску, о том, что Facebook и Instagram 
*признаны экстремистскими организациями и запрещены на территории РФ

**Comment by Shibbaa** [comment]
Выполнил

**Comment by Soulbrain24** [comment]
Спасибо, всё верно
